<?php


function lenbox_cbnx_get_form_fields()
{
	return array(
		'live_client_id'      => array(
			'title' => __('Client ID / VD', 'lenbox-cbnx'),
			'type'  => 'text',
		),
		'live_client_authkey' => array(
			'title' => __('Authkey', 'lenbox-cbnx'),
			'type'  => 'text',
		),
		'use_test'            => array(
			'title'       => __('Use test environment', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'checkbox',
			'description' => '',
			'default'     => 'no',
		),
		'show_eligibility' => array(
			'title'       => __('Show Eligibilities', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'checkbox',
			'description' => '',
			'default'     => 'no',
		),
		// Descriptive fields
		'title'               => array(
			'title'       => __('Nom affiché au client', 'lenbox-cbnx'),
			'type'        => 'text',
			'description' => '',
			'default'     => __('Paiement en plusieurs fois', 'lenbox-cbnx'),
			'desc_tip'    => true,
		),
		'description'         => array(
			'title'       => __('Description', 'lenbox-cbnx'),
			'type'        => 'textarea',
			'description' => __('Description du paiement destinée au client', 'lenbox-cbnx'),
			'default'     => __('Payer en plusieurs fois', 'lenbox-cbnx'),
		),
		'client_label'        => array(
			'title'       => __('Afficher les options disponible', 'lenbox-cbnx'),
			'type'        => 'checkbox',
			'description' => __('Les clients peuvent choisir le produit (3X/4X/..) depuis la page de paiement', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		// Product configuration
		'cbnx3_payant'        => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 3X ' . __('avec frais', 'lenbox-cbnx') . ' (3XP)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 3XP',
			'default'     => 'no',
		),
		'cbnx3_payant_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 3XP : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 3XP',
			'default'     => 0,
		),
		'cbnx3_payant_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 3XP : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 3XP',
			'default'     => 0,
		),
		'cbnx3_gratuit'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 3X ' . __('sans frais', 'lenbox-cbnx') . ' (3XG)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . '3X sans frais',
			'default'     => 'no',
		),
		'cbnx3_gratuit_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 3XG : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 3XG',
			'default'     => 0,
		),
		'cbnx3_gratuit_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 3XG : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 3XG',
			'default'     => 0,
		),
		'cbnx4_payant'    => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 4X ' . __('avec frais', 'lenbox-cbnx') . ' (4XP)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 4XP',
			'default'     => 'no',
		),
		'cbnx4_payant_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 4XP : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 4XP',
			'default'     => 0,
		),
		'cbnx4_payant_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 4XP : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 4XP',
			'default'     => 0,
		),
		'cbnx4_gratuit'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 4X ' . __('avec frais', 'lenbox-cbnx') . ' (4XG)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 4X ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx4_gratuit_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 4X :' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 4XG',
			'default'     => 0,
		),
		'cbnx4_gratuit_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 4X sans frais :' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 4XG',
			'default'     => 0,
		),
		'cbnx10_payant'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 10X ' . __('avec frais', 'lenbox-cbnx') . ' (10XP)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 10X' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx10_payant_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 10XP : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 10XP',
			'default'     => 0,
		),
		'cbnx10_payant_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 10XP : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 10XP',
			'default'     => 0,
		),
		'cbnx10_gratuit'      => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 10X ' . __('sans frais', 'lenbox-cbnx') . ' (10XG)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 10X '  . __('sans frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx10_gratuit_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 10XG : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 10XG',
			'default'     => 0,
		),
		'cbnx10_gratuit_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 10XG : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 10XG',
			'default'     => 0,
		),
		// 12X
		'cbnx12_payant'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 12x ' . __('avec frais', 'lenbox-cbnx') . ' (12XP)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 12X ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx12_payant_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 12XP : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 12x ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx12_payant_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 12XP : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 12x ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx12_gratuit'      => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 12X ' . __('avec frais', 'lenbox-cbnx') . ' (12XG)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 12x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx12_gratuit_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 12XG : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 12x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx12_gratuit_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 12XG : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 12x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		// 24X
		'cbnx24_payant'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 24x ' . __('avec frais', 'lenbox-cbnx') . ' (24XP)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 24X ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx24_payant_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 24XP : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 24x ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx24_payant_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 24XP : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 24x ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx24_gratuit'      => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 24X ' . __('avec frais', 'lenbox-cbnx') . ' (24XG)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 24x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx24_gratuit_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 24XG : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 24x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx24_gratuit_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 24XG : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 24x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		// 36X
		'cbnx36_payant'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 36x ' . __('avec frais', 'lenbox-cbnx') . ' (36XP)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 36X ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx36_payant_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 36XP : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 36x ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx36_payant_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 36XP : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 36x ' . __('avec frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx36_gratuit'      => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 36X ' . __('avec frais', 'lenbox-cbnx') . ' (36XG)',
			'label'       => '',
			'type'        => 'checkbox',
			'description' => __('Activer le paiement en', 'lenbox-cbnx') . ' 36x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 'no',
		),
		'cbnx36_gratuit_min'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 36XG : ' . __('Seuil minimum', 'lenbox-cbnx'),
			'label'       => '',
			'type'        => 'number',
			'min'         => 0,
			'description' => __('Montant minimum pour afficher le paiement en', 'lenbox-cbnx') . ' 36x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 0,
		),
		'cbnx36_gratuit_max'       => array(
			'title'       => __('Paiment en', 'lenbox-cbnx') . ' 36XG : ' . __('Seuil maximum', 'lenbox-cbnx'),
			'label'       => '',
			'min'         => 0,
			'type'        => 'number',
			'description' => __('Montant maximum pour afficher le paiement en', 'lenbox-cbnx') . ' 36x ' . __('sans frais', 'lenbox-cbnx'),
			'default'     => 0,
		),

	);
}
